#!/usr/bin/env python3

import os
import xml.dom.minidom


def fix_basedir():
    current_dir = os.path.dirname(os.path.abspath(__file__))
    most_dir = os.path.join(current_dir, "MoST")
    launchd_path = os.path.join(current_dir, "most.launchd.xml")

    tree = xml.dom.minidom.parse(launchd_path)
    config = tree.documentElement

    basedir_nodes = config.getElementsByTagName("basedir")
    if len(basedir_nodes) == 0:
        basedir_node = tree.createElement("basedir")
        basedir_node.setAttribute("path", most_dir)
        config.appendChild(basedir_node)
    else:
        basedir_node = basedir_nodes[0]
        basedir_node.setAttribute("path", most_dir)

    with open(launchd_path, "w") as f:
        tree.writexml(f)


if __name__ == '__main__':
    fix_basedir()
